/* DW */
/* create fact table*/
CREATE OR REPLACE TABLE FACT_CORRELATIONS_DAILY (
FACT_CORRELATIONS_DAILYID INT PRIMARY KEY IDENTITY
,DD_CALENDARDATE DATE /* grain */
,CT_FASTINGHOURS INT
,CT_INTENSITYMINUTES INT
,CT_SLEEPSCORE INT
,CT_STRESS INT );
/* insert the structure from FastingData table along with FastingHours */
INSERT INTO FACT_CORRELATIONS_DAILY (DD_CALENDARDATE,CT_FASTINGHOURS)
SELECT CALENDARDATE, FASTINGHOURS
FROM ODS.FASTINGDATA;
/* append the IntensityMinutes for each day */
UPDATE DW.FACT_CORRELATIONS_DAILY F
SET F.CT_INTENSITYMINUTES = I.INTENSITYMINUTES
FROM ODS.INTENSITYMINUTESDATA I
WHERE F.DD_CALENDARDATE = I.CALENDARDATE;
/* append the SleepHours for each day */
UPDATE DW.FACT_CORRELATIONS_DAILY F
SET F.CT_SLEEPSCORE = SL.SLEEPSCORE
FROM ODS.SLEEPDATA SL
WHERE F.DD_CALENDARDATE = SL.CALENDARDATE;
/* append the AvgStress for each day */
UPDATE DW.FACT_CORRELATIONS_DAILY F
SET F.CT_STRESS = ST.STRESS
FROM ODS.STRESSDATA ST
WHERE F.DD_CALENDARDATE = ST.CALENDARDATE;
